### ISSUE TITLE
What are the steps to use it in Android?

### ISSUE THREAD

**Issue by jjvargas** [datitran/object_detector_app#1]

**Comment by datitran** [comment]
I'm not an Android developer but there is an official example on their [Git repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android). Also I found two good examples [here](https://blog.mindorks.com/android-tensorflow-machine-learning-example-ff0e9b2654cc) and [here](https://omid.al/posts/2017-02-20-Tutorial-Build-Your-First-Tensorflow-Android-App.html).

**Comment by shamanez** [comment]
@jjvargas  Did you try this on android . With an android device what would be the fps in the application ?
