### ISSUE TITLE
Using tensorbox model

### ISSUE THREAD

**Issue by Zumbalamambo** [datitran/object_detector_app#12]
How do we use tensorbox model with Object-Detector-App?

**Comment by datitran** [comment]
Tensorbox is another project. I'm using Google's Tensorflow Object Recognition API. They are both different. If you want to use Tensorbox models, you need to adjust the `object_detection_app.py` script as the output of the Tesorbox model is different than from mine.

**Comment by Zumbalamambo** [comment]
Can you share with me the model file of tensorbox, if you have one? I wish to detect heads and faces. Do you have any model that I can use to detect them?

**Comment by datitran** [comment]
Uhmm no sorry I don't have one at hand. Please have a look at the tensorbox code and save the model by yourself. By the way, if you just want to detect faces, you can use [Dlib's Face Detector](http://dlib.net/face_detector.py.html) with OpenCV. It's already pretty good...

**Comment by Zumbalamambo** [comment]
Ya thank you. but Im trying to detect the faces of pedestrians. Do you have any pedestrian specific files?

**Comment by datitran** [comment]
Dlib uses HOG and a liner classifier under the hood. It doesn't matter if those are pedestrians. They should be recognized as well...
