### ISSUE TITLE
custom object / model training question

### ISSUE THREAD

**Issue by lhammond** [datitran/object_detector_app#13]
Very cool project! .. I have it running on a raspi.  Worked like a charm.

I've been using some opencv template matching for a simple object detection system, but may consider this approach.

Can you point me in the right direction on how I would train the system to detect a custom object?
Take a hotdog for example .. no bun, just the hotdog meat.  Is it possible to create a training set with my own images and import into the project so that I can improve the detection results?

I'm guessing, I'd need to create a training set, then retrain the system?

thanks and great blog post/project!

**Comment by datitran** [comment]
Cool great that you find this useful. Concerning your question to detect a custom object, have a look at my recent [article](https://medium.com/towards-data-science/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9).

**Comment by lhammond** [comment]
thanks!!  I've made it through the process and am trying to upload to google cloud.  It seems like the protos generated by protoc aren't being included in the dist package...should they be?

**Comment by datitran** [comment]
Hmm they are. Have a look at the [`BUILD`](https://github.com/datitran/models/blob/master/object_detection/BUILD).

**Comment by shamanez** [comment]
@lhammond  Did you try it on an android ? How did you run it on raspberry pie ? Locally or with an API .

**Comment by lhammond** [comment]
@shamanez : I ran it on the pi in a virtualenv
