### ISSUE TITLE
Object-Detector-App import cv2 No module named 'cv2'

### ISSUE THREAD

**Issue by radzfoto** [datitran/object_detector_app#14]
Hi Datritan. I have Tensorflow object detection demo and sample code working on Ubuntu 16.04, so I thought I would try your project to improve performance. However, I've run into two errors:
1. menpo::tbb=4.3_20141023=0 in environment.yml generates this error:

Error: NoPackagesFoundError: Package missing in current linux-64 channels: 
  - tbb 4.3_20141023 0
I "fixed" this by changing the line to "mempo:ttb" and removing the rest. I have no idea if this is good or bad, but the environment appeared to install without errors.

2. After installing the environment as in 1. above, I tried to run "python object_detection_app.py" but I got the following error:
  File "object_detection_app.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

If you have any suggestions how to resolve this, I would appreciate it very much. Thank you.

**Comment by datitran** [comment]
Well the `environment.yml` file was created for OSX so that's why not every package is available on the linux-64 channels. In terms of the error, you just need to install OpenCV.

**Comment by wxyfish** [comment]
I think you did not read the output after conda.    You need make the environment activate like this
   $ source activate object-detection  
after that you can python .......
This works on my PC.  :-)

**Comment by radzfoto** [comment]
Actually I did activate. I did realize, however, that I was building on Ubuntu and not OSX so there might be differences so I can't use environment.yml. I am trying to build new project from scratch now like you did originally. In particular, I found that my opencv installation had not installed properly. I spent a couple of days and finally have a clean installation of opencv 3.2 (with CUDA) on Ubuntu as wwell as Tensorflow 1.2. I'm using that as a base. I'll let you know how it goes with the other components.

**Comment by wxyfish** [comment]
But,  I am working on Ubuntu 16.04.    Before try datitran's app,  I have opencv work well in python3.    After cuda the environment,  opencv could not work in python3 anymore, but works in the environment.   And I try to install opencv-python outside the environment, it does not work.
