### ISSUE TITLE
Can i detect on my own video?

### ISSUE THREAD

**Issue by babymilo** [datitran/object_detector_app#15]
Can i detect on my own video?

**Comment by datitran** [comment]
Yes sure have a look at this [code snippet](https://gist.github.com/datitran/90cb3accb8d35148ab3d4d4f9360b0d4). You just need to replace the video source with your video.

**Comment by babymilo** [comment]
I got error when i running your code .
Traceback (most recent call last):
  File "po.py", line 70, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'TensorArrayV3'

**Comment by datitran** [comment]
Hey this seems to be related to this issue: https://github.com/tensorflow/models/issues/1603. I also use Python 3.5 so probably this is because you're using 2.7.

**Comment by babymilo** [comment]
I try to running with Python 2.7 again.It work! 

Thank you very much

**Comment by babymilo** [comment]
How to detect with Traffic Sign?

**Comment by datitran** [comment]
Well you need to train a model that is able to detect traffic signs. Either you collect the data by yourself and then you fine-tune it (also check my [new article](https://medium.com/towards-data-science/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9) on how to do it) or you need to research if there is a already a dataset for this and then also do the fine-tuning.
