### ISSUE TITLE
how to create the model.ckpt

### ISSUE THREAD

**Issue by lhammond** [datitran/object_detector_app#18]
I'm unclear on how the model.ckpt file is generated

any direction is greatly appreciated!

**Comment by datitran** [comment]
The checkpoint is created regularly. Have a look at the [`train.py`](https://github.com/datitran/models/blob/master/object_detection/train.py) and [`trainer.py`](https://github.com/datitran/models/blob/master/object_detection/trainer.py). In the `train.py`, you can see that `train_dir` is an argument for `trainer.train` and looking at the `trainer.py`, you can see that it takes the [`train.proto`](https://github.com/datitran/models/blob/master/object_detection/protos/train.proto) for all the settings like how frequently to keep checkpoints etc... Hope this helps!

**Comment by lhammond** [comment]
ok thanks, so when I'm training in Google's cloud, the model.ckpt file will be automatically created?

**Comment by datitran** [comment]
Yes it will be created in the bucket that you define for storing the checkpoint, usually it is the `train_dir`.

**Comment by lhammond** [comment]
making progress .. this is from my own dataset/training.  I've loaded the inference graph into the app filesystem, but haven't seen my objects being detected yet

![image](https://user-images.githubusercontent.com/229602/28949813-3850b9ce-788d-11e7-9bd4-35a273514ce9.png)

**Comment by datitran** [comment]
Hmm what are you detecting anyways? What is your evaluation showing? Have you run the `evaluation` as well and looked at the detected images for the validation part. By the way, in the `object_detection_app.py` script you have the `vis_util.visualize_boxes_and_labels_on_image_array`function which also takes `min_score_thresh` as threshold. Its default value is 0.5 but you could lower it. Maybe the detected video is hard to detect and the probability is just low.

**Comment by lhammond** [comment]
I just have a little toy hotdog that was sitting here that I had somebody take a bunch of images of.  I think one thing is that they built a little rig to hold the camera with a flash...I think that the homogeneity of the images may be impacting the detection too.   I'm going to do another training set with pictures I take from more angles and lighting and also use some google images.  Also, btw, I scaled the images from 20Mb down to around 300x280 before annotating them.

**Comment by datitran** [comment]
Cool, scaling is fine.. looking forward to seeing your final results!

**Comment by lhammond** [comment]
I created a new file object_detection/data/my_labels.pbtxt and added my class, then changed the path in object_detection_app.py .. it appears that I'm getting some detection now, although I have to have the camera oriented a certain way.  I'm going to start working on expanding the training set today.  Getting there!   I think this is correct as my class label ID was 1 and I was getting a person being detected, which is ID 1 in the mscoco pbtxt.  Thoughts?

**Comment by shamanez** [comment]
@lhammond  @datitran  In the tensor-board loss graphs what is the light colour graph ?

**Comment by datitran** [comment]
@shamanez The light colour graph shows the actual point for each step whereas the other is an average.
