### ISSUE TITLE
I am not using Anaconda. So is there a way that I can do the same thing with out anaconda?

### ISSUE THREAD

**Issue by shamanez** [datitran/object_detector_app#19]
@datitran  This is really useful . I actually trained a ssd with mobilenet for my own data set but still I have issues with FPS. So your medium post did help me a lot . 

Can you explain me what is environment.yml file and why we need to conda env variable to execute that ?

**Comment by talamoin** [comment]
@shamanez anaconda includes pip + virtualenv (+ virtualenvwrapper) it can work without using anaconda but it'll require some workarounds , the environment.yml keeps your project's dependencies clean and separated from your global site-packages

**Comment by shamanez** [comment]
I have already installed my TF in a separate environment . So do I still need anaconda or can I continue with the way I am doing ? 

> conda env create -f environment.yml

So basically above command is for have an environment will all the dependencies installed before running the code. So if I don't use anaconda I have to install the dependencies manually .  

Am I right ?

**Comment by datitran** [comment]
@shamanez As @talamoin said the `environment.yml` file is to keep your project's dependencies clean which means that you of course can also manually install all the dependencies yourself. In your case, if you already installed everything in a separate environment, then you can continue with what you're doing.
