### ISSUE TITLE
Getting issue while running code

### ISSUE THREAD

**Issue by rajeevraibhatia** [datitran/object_detector_app#2]
I'm getting the below error while running the code:

/usr/bin/python3.5 /home/deeplearning/Object-Detector-App/object_detection_app.py
Traceback (most recent call last):
  File "/home/deeplearning/Object-Detector-App/object_detection_app.py", line 26, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "/home/deeplearning/Object-Detector-App/object_detection/utils/label_map_util.py", line 107, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 472, in Merge
    text.split('\n'),
TypeError: a bytes-like object is required, not 'str'

**Comment by datitran** [comment]
What TensorFlow version are you using? Another user had the same problem but he was using TensorFlow 1.0. I replicated this on my Mac and got the same error. If this is the case upgrade to 1.2.

**Comment by ghost** [comment]
@rajeevraibhatia you might want to just try recompiling protocol buffers using the protoc command as a first pass.  The repo contains protoc which might be incompatible with your version of protobuf.

**Comment by gabrieledcjr** [comment]
Update code utils/label_map_util.py line 107 to

`text_format.Merge(label_map_string.decode('utf8'), label_map)`
