### ISSUE TITLE
Protobuf Window installation 

### ISSUE THREAD

**Issue by mrnameless123** [datitran/object_detector_app#21]
this issue is not related to your project but I would really appreciate if you could provide the instruction to install protobuf on windows OS. 
Thank you

**Comment by datitran** [comment]
Sorry but this is better asked on Stackoverflow.

**Comment by debihiga** [comment]
Hi, it's not a problem related with the project, but here is an answer.
1. Download protoc-3.4.0-win32.zip from [here](https://github.com/google/protobuf/releases/tag/v3.4.0)
I tried with 3.6.0 and didn't work. See issue [here](https://github.com/tensorflow/models/issues/2930).
2. Extract and move bin/protoc.exe to this project's folder.
3. Run
`.\protoc.exe object_detection/protos/*.proto --python_out=. `
