### ISSUE TITLE
How to switch back to OpenCV 3.0 

### ISSUE THREAD

**Issue by l-chenyao** [datitran/object_detector_app#22]
Note: If you are on Mac OSX like me and you’re using OpenCV 3.1, there might be a chance that OpenCV’s VideoCapture crashes after a while. There is already an issue filed. Switching back to OpenCV 3.0 solved the issue though.

Up is your note, 
my environment is win7， anaconda 4.2, openCV3.1
Every time I run "python object_detection_app.py",  computer is crash.
You have noted that we need "Switching back to OpenCV 3.0 " to solve this problem.

**My question is below** 
    I use this command to install opencv "conda install -c menpo opencv3", it auto install 3.1version .
    SO, how to switch back to OpenCV 3.0  (my environment is win7， anaconda 4.2, openCV3.1)

Thank you very much

**Comment by datitran** [comment]
Menpo only has 3.1 I think, you have to search for a channel were you get 3.0. So just remove the 3.1 version and then install it with a different channel.

**Comment by l-chenyao** [comment]
Thanks for your reply, it is help me.

I use this command to install opencv 3.0.0    "conda install -c memex opencv"
![image](https://user-images.githubusercontent.com/19616540/29575599-9303878e-8797-11e7-8ab6-2eccd09391fe.png)
