### ISSUE TITLE
video in out_q may not in right order?

### ISSUE THREAD

**Issue by scotthuang1989** [datitran/object_detector_app#31]
after reading your code. I think If I use multiple thread/process to do detection. the video frame in out_q may not be in the right order, am I right?

**Comment by QianyuanLiu** [comment]
multiple thread/process would not improve the perform.

**Comment by scotthuang1989** [comment]
I have another [project ](https://github.com/scotthuang1989/object_detection_with_tensorflow)that tried multiple-process . I also did some experiments. My current summary is that multi-process can approve it but it consumes multiple times of system ram and it depends on the GPU.
